class CfgPatches
{
	class TripSeventh_OPFOR_Units_DrugCartel
	{
		units[]=
		{
			"TripSeventh_OPFOR_Medic",
			"TripSeventh_OPFOR_Radioman",
			"TripSeventh_OPFOR_Pilot",
			"TripSeventh_OPFOR_Rifleman_AR",
			"TripSeventh_OPFOR_Rifleman_BR",
			"TripSeventh_OPFOR_Rifleman_AT",
			"TripSeventh_OPFOR_Rifleman_Light",
			"TripSeventh_OPFOR_AT_Specialist",
			"TripSeventh_OPFOR_AA_Specialist",
			"TripSeventh_OPFOR_Engineer",
			"TripSeventh_OPFOR_Breacher",
			"TripSeventh_OPFOR_TeamLead",
			"TripSeventh_OPFOR_SquadLead",
			"TripSeventh_OPFOR_Grenadier",
			"TripSeventh_OPFOR_Autorifleman",
			"TripSeventh_OPFOR_Assist_Autorifleman",
			"TripSeventh_OPFOR_Marksman",
			"TripSeventh_OPFOR_Sniper",
			"TripSeventh_OPFOR_Observer",
			"TripSeventh_OPFOR_Crewman",
			"TripSeventh_OPFOR_Demolitions",
			"TripSeventh_OPFOR_UAV_Op",
			"TripSeventh_OPFOR_Unarmed",
			"TripSeventh_OPFOR_Officer",
			"TripSeventh_OPFOR_Breacher2"
		};
		weapons[]=
		{
			
		};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"OPTRE_Ins_Units"
		};
		addonRootClass="OPTRE_Ins_Units";
	};
};
class CfgVehicles
{
	class CAManBase;
	class SoldierWB: CAManBase
	{
		class HitPoints;
	};
	class OPTRE_UNSC_Soldier_Base: SoldierWB
	{
		class EventHandlers;
		class HitPoints: HitPoints
		{
			class HitFace;
			class HitNeck;
			class HitHead;
			class HitPelvis;
			class HitAbdomen;
			class HitDiaphragm;
			class HitChest;
			class HitBody;
			class HitArms;
			class HitHands;
			class HitLegs;
		};
	};
	class TripSeventh_OPFOR_Soldier_Base: OPTRE_UNSC_Soldier_Base
	{
		dlc="OPTRE";
		author="Den";
		scope=1;
		scopeCurator=0;
		faction="T7th_Ins";
		side=0;
		vehicleClass="OPTRE_Ins_Man_URF_class";
		uniformClass="OPTRE_Ins_URF_Combat_Uniform";
		model="\OPTRE_Ins_Units\URF\uniform.p3d";
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		Items[]=
		{
			"OPTRE_Biofoam"
		};
		RespawnItems[]=
		{
			"OPTRE_Biofoam"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG"
		};
		identityTypes[]=
		{
			"LanguageENG_F",
			"LanguageENGB_F",
			"LanguageENGFRE_F",
			"LanguageGRE_F",
			"Kerry",
			"EPA_B_Northgate",
			"EPA_B_Hardy",
			"EPA_B_James",
			"EPA_B_McKay",
			"Head_Greek",
			"Head_African",
			"Head_Euro",
			"Head_Asian",
			"Head_NATO",
			"Head_Tanoan",
			"Head_Enoch",
			"Head_Russian",
			"G_INS_default"
		};
		hiddenSelections[]=
		{
			"camoUni",
			"camoBelt"
		};
		hiddenSelectionsTextures[]=
		{
			"optre_ins_units\urf\data\uniform_co.paa",
			"optre_ins_units\urf\data\belt_co.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat"
			};
		};
		class HitPoints: HitPoints
		{
			class HitFace: HitFace
			{
			};
			class HitNeck: HitNeck
			{
				armor=3;
			};
			class HitHead: HitHead
			{
			};
			class HitPelvis: HitPelvis
			{
				armor=3;
			};
			class HitAbdomen: HitAbdomen
			{
				armor=3;
			};
			class HitDiaphragm: HitDiaphragm
			{
				armor=3;
			};
			class HitChest: HitChest
			{
				armor=3;
			};
			class HitBody: HitBody
			{
			};
			class HitArms: HitArms
			{
				armor=3;
			};
			class HitHands: HitHands
			{
				armor=3;
			};
			class HitLegs: HitLegs
			{
				armor=3;
			};
		};
		editorSubcategory="OPTRE_EditorSubcategory_MenURF";
	};
	
	class TripSeventh_OPFOR_Medic: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Medic";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		attendant=1;
		icon="iconManMedic";
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		respawnlinkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		backpack="OPTRE_B_TacticalPack_blk_Medic";
		weapons[]=
		{
			"OPTRE_MA5A",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_MA5A",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow"
		};
		respawnMagazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow"
		};
	};
	class TripSeventh_OPFOR_Radioman: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Radio Operator";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		role="RadioOperator";
		backpack="OPTRE_ANPRC_521_URF";
		weapons[]=
		{
			"OPTRE_M7",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_M7",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_orange",
			"OPTRE_M2_Smoke_green"
		};
		respawnMagazines[]=
		{
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_orange",
			"OPTRE_M2_Smoke_green"
		};
	};
	class TripSeventh_OPFOR_Pilot: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		author="Article 2 Studios";
		displayName="Pilot";
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		respawnlinkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		weapons[]=
		{
			"OPTRE_M6G_SF",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_M6G_SF",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_orange",
			"OPTRE_M2_Smoke_green"
		};
		respawnMagazines[]=
		{
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_orange",
			"OPTRE_M2_Smoke_green"
		};
	};
	class TripSeventh_OPFOR_Rifleman_AR: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Rifleman (MA5)";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		respawnlinkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		weapons[]=
		{
			"OPTRE_MA5A",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_MA5A",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
		respawnMagazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
	};
	class TripSeventh_OPFOR_Rifleman_BR: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Rifleman (BR45)";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		respawnlinkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		weapons[]=
		{
			"OPTRE_BR45",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_BR45",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
		respawnMagazines[]=
		{
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
	};
	class TripSeventh_OPFOR_Rifleman_AT: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Rifleman (AT)";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		backpack="OPTRE_B_TacticalPack_blk_M41";
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		respawnlinkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		weapons[]=
		{
			"OPTRE_MA5A",
			"Throw",
			"Put",
			"OPTRE_M41_SSR"
		};
		respawnWeapons[]=
		{
			"OPTRE_MA5A",
			"Throw",
			"Put",
			"OPTRE_M41_SSR"
		};
		magazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_M41_Twin_HEAT",
			"OPTRE_M41_Twin_HEAT",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
		respawnMagazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_M41_Twin_HEAT",
			"OPTRE_M41_Twin_HEAT",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
		icon="iconManAT";
	};
	class TripSeventh_OPFOR_Rifleman_Light: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Rifleman (Light)";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_Booniehat_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_oli",
			"H_Booniehat_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		weapons[]=
		{
			"OPTRE_MA5A",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_MA5A",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
		respawnMagazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
	};
	class TripSeventh_OPFOR_AT_Specialist: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="AT Specialist";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		respawnlinkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		backpack="OPTRE_B_TacticalPack_blk_M41G";
		weapons[]=
		{
			"OPTRE_MA5A",
			"Throw",
			"Put",
			"OPTRE_M41_SSR_G"
		};
		respawnWeapons[]=
		{
			"OPTRE_MA5A",
			"Throw",
			"Put",
			"OPTRE_M41_SSR_G"
		};
		magazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_M41_Twin_HEAT_Thermal",
			"OPTRE_M41_Twin_HEAT_Thermal",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
		respawnMagazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_M41_Twin_HEAT_Thermal",
			"OPTRE_M41_Twin_HEAT_Thermal",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
		icon="iconManAT";
	};
	class TripSeventh_OPFOR_AA_Specialist: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="AA Specialist";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		respawnlinkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		backpack="OPTRE_B_TacticalPack_blk_M41G";
		weapons[]=
		{
			"OPTRE_MA5A",
			"Throw",
			"Put",
			"OPTRE_M41_SSR_G"
		};
		respawnWeapons[]=
		{
			"OPTRE_MA5A",
			"Throw",
			"Put",
			"OPTRE_M41_SSR_G"
		};
		magazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_M41_Twin_HEAT_Thermal",
			"OPTRE_M41_Twin_HEAT_Thermal",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
		respawnMagazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_M41_Twin_HEAT_Thermal",
			"OPTRE_M41_Twin_HEAT_Thermal",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
		icon="iconManAT";
	};
	class TripSeventh_OPFOR_Engineer: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Engineer";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		engineer=1;
		backpack="OPTRE_B_TacticalPack_blk_Demo";
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		respawnlinkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		weapons[]=
		{
			"OPTRE_m45",
			"Throw",
			"Put",
			"OPTRE_M6G_SF"
		};
		respawnWeapons[]=
		{
			"OPTRE_m45",
			"Throw",
			"Put",
			"OPTRE_M6G_SF"
		};
		magazines[]=
		{
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs"
		};
		respawnMagazines[]=
		{
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs"
		};
		icon="iconManEngineer";
	};
	class TripSeventh_OPFOR_Breacher: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Breacher";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		respawnlinkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		weapons[]=
		{
			"OPTRE_m45",
			"Throw",
			"Put",
			"OPTRE_M6G_SF"
		};
		respawnWeapons[]=
		{
			"OPTRE_m45",
			"Throw",
			"Put",
			"OPTRE_M6G_SF"
		};
		magazines[]=
		{
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs"
		};
		respawnMagazines[]=
		{
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs"
		};
	};
	class TripSeventh_OPFOR_Breacher2: TripSeventh_OPFOR_Breacher
	{
		displayName="Breacher 2";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		weapons[]=
		{
			"OPTRE_CQS48_Bulldog_Automatic_Innie",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_CQS48_Bulldog_Automatic_Innie",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_12Rnd_12Gauge_Pellets",
			"OPTRE_12Rnd_12Gauge_Pellets",
			"OPTRE_12Rnd_12Gauge_Pellets",
			"OPTRE_12Rnd_12Gauge_Pellets",
			"OPTRE_12Rnd_12Gauge_Pellets",
			"OPTRE_12Rnd_12Gauge_Pellets"
		};
		respawnMagazines[]=
		{
			"OPTRE_12Rnd_12Gauge_Pellets",
			"OPTRE_12Rnd_12Gauge_Pellets",
			"OPTRE_12Rnd_12Gauge_Pellets",
			"OPTRE_12Rnd_12Gauge_Pellets",
			"OPTRE_12Rnd_12Gauge_Pellets",
			"OPTRE_12Rnd_12Gauge_Pellets"
		};
	};
	class TripSeventh_OPFOR_TeamLead: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Team Leader";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		respawnlinkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		weapons[]=
		{
			"OPTRE_M295_BMR",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_M295_BMR",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_25Rnd_762x51_AP_Mag_Tracer",
			"OPTRE_25Rnd_762x51_AP_Mag_Tracer",
			"OPTRE_25Rnd_762x51_AP_Mag_Tracer",
			"OPTRE_25Rnd_762x51_AP_Mag_Tracer",
			"OPTRE_25Rnd_762x51_AP_Mag_Tracer",
			"OPTRE_25Rnd_762x51_AP_Mag_Tracer",
			"OPTRE_25Rnd_762x51_AP_Mag_Tracer",
			"OPTRE_25Rnd_762x51_AP_Mag_Tracer",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_orange",
			"OPTRE_M2_Smoke_green"
		};
		respawnMagazines[]=
		{
			"OPTRE_25Rnd_762x51_AP_Mag_Tracer",
			"OPTRE_25Rnd_762x51_AP_Mag_Tracer",
			"OPTRE_25Rnd_762x51_AP_Mag_Tracer",
			"OPTRE_25Rnd_762x51_AP_Mag_Tracer",
			"OPTRE_25Rnd_762x51_AP_Mag_Tracer",
			"OPTRE_25Rnd_762x51_AP_Mag_Tracer",
			"OPTRE_25Rnd_762x51_AP_Mag_Tracer",
			"OPTRE_25Rnd_762x51_AP_Mag_Tracer",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_orange",
			"OPTRE_M2_Smoke_green"
		};
		icon="iconManLeader";
	};
	class TripSeventh_OPFOR_SquadLead: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Squad Leader";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		respawnlinkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		weapons[]=
		{
			"OPTRE_MA5BGL",
			"OPTRE_M6G_SF",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_MA5BGL",
			"OPTRE_M6G_SF",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_60Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_orange",
			"OPTRE_M2_Smoke_green",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"OPTRE_60Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_orange",
			"OPTRE_M2_Smoke_green",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell"
		};
		icon="iconManLeader";
	};
	class TripSeventh_OPFOR_Grenadier: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Grenadier";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		respawnlinkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		weapons[]=
		{
			"OPTRE_MA5AGL",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_MA5AGL",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell"
		};
	};
	class TripSeventh_OPFOR_Autorifleman: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Autorifleman";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		respawnlinkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		backpack="OPTRE_B_TacticalPack_blk_M73";
		weapons[]=
		{
			"OPTRE_M73",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_M73",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_100Rnd_95x40_Box_Tracer_Yellow",
			"OPTRE_100Rnd_95x40_Box_Tracer_Yellow",
			"OPTRE_100Rnd_95x40_Box_Tracer_Yellow",
			"OPTRE_100Rnd_95x40_Box_Tracer_Yellow",
			"OPTRE_100Rnd_95x40_Box_Tracer_Yellow",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
		respawnMagazines[]=
		{
			"OPTRE_100Rnd_95x40_Box_Tracer_Yellow",
			"OPTRE_100Rnd_95x40_Box_Tracer_Yellow",
			"OPTRE_100Rnd_95x40_Box_Tracer_Yellow",
			"OPTRE_100Rnd_95x40_Box_Tracer_Yellow",
			"OPTRE_100Rnd_95x40_Box_Tracer_Yellow",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
		icon="iconManMG";
	};
	class TripSeventh_OPFOR_Assist_Autorifleman: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Assistant Autorifleman";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		respawnlinkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		backpack="OPTRE_B_TacticalPack_blk_M73";
		weapons[]=
		{
			"OPTRE_MA5A",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_MA5A",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow"
		};
		respawnMagazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_32Rnd_762x51_Mag_Tracer_Yellow"
		};
	};
	class TripSeventh_OPFOR_Marksman: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Designated Marksman";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		weapons[]=
		{
			"OPTRE_M392_DMR_ScopedRifle",
			"OPTRE_M6G_SF",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_M392_DMR_ScopedRifle",
			"OPTRE_M6G_SF",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_15Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_15Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_15Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_15Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_15Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_15Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_15Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_15Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		respawnMagazines[]=
		{
			"OPTRE_15Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_15Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_15Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_15Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_15Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_15Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_15Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_15Rnd_762x51_Mag_Tracer_Yellow",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
	};
	class TripSeventh_OPFOR_Sniper: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Sniper";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		weapons[]=
		{
			"OPTRE_SRS99D_SC_LS",
			"OPTRE_M6G_SF",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_SRS99D_SC_LS",
			"OPTRE_M6G_SF",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_4Rnd_145x114_APFSDS_Mag",
			"OPTRE_4Rnd_145x114_APFSDS_Mag",
			"OPTRE_4Rnd_145x114_APFSDS_Mag",
			"OPTRE_4Rnd_145x114_APFSDS_Mag",
			"OPTRE_4Rnd_145x114_APFSDS_Mag",
			"OPTRE_4Rnd_145x114_APFSDS_Mag",
			"OPTRE_4Rnd_145x114_APFSDS_Mag",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
		respawnMagazines[]=
		{
			"OPTRE_4Rnd_145x114_APFSDS_Mag",
			"OPTRE_4Rnd_145x114_APFSDS_Mag",
			"OPTRE_4Rnd_145x114_APFSDS_Mag",
			"OPTRE_4Rnd_145x114_APFSDS_Mag",
			"OPTRE_4Rnd_145x114_APFSDS_Mag",
			"OPTRE_4Rnd_145x114_APFSDS_Mag",
			"OPTRE_4Rnd_145x114_APFSDS_Mag",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
	};
	class TripSeventh_OPFOR_Observer: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Observer";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		Items[]=
		{
			"OPTRE_Biofoam",
			"Item_Laserdesignator"
		};
		RespawnItems[]=
		{
			"OPTRE_Biofoam",
			"Item_Laserdesignator"
		};
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		respawnlinkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		weapons[]=
		{
			"OPTRE_BR55HB_ScopedRifle",
			"OPTRE_M6G_SF",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_BR55HB_ScopedRifle",
			"OPTRE_M6G_SF",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"Laserbatteries",
			"APERSTripMine_Wire_Mag",
			"ClaymoreDirectionalMine_Remote_Mag"
		};
		respawnMagazines[]=
		{
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"Laserbatteries",
			"APERSTripMine_Wire_Mag",
			"ClaymoreDirectionalMine_Remote_Mag"
		};
	};
	class TripSeventh_OPFOR_Crewman: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Crewman";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		weapons[]=
		{
			"OPTRE_M7",
			"OPTRE_M6G_SF",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_M7",
			"OPTRE_M6G_SF",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		respawnlinkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		magazines[]=
		{
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
		respawnMagazines[]=
		{
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_60Rnd_5x23mm_Mag_Tracer_Yellow",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
	};
	class TripSeventh_OPFOR_Demolitions: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Demolitions";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		engineer=1;
		backpack="OPTRE_B_TacticalPack_blk_Demo";
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		respawnlinkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		weapons[]=
		{
			"OPTRE_m45",
			"Throw",
			"Put",
			"OPTRE_M6G_SF"
		};
		respawnWeapons[]=
		{
			"OPTRE_m45",
			"Throw",
			"Put",
			"OPTRE_M6G_SF"
		};
		magazines[]=
		{
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag"
		};
		respawnMagazines[]=
		{
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag"
		};
		icon="iconManExplosive";
	};
	class TripSeventh_OPFOR_UAV_Op: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="UAV Operator";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		backpack="O_UAV_01_backpack_F";
		uavHacker=1;
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		respawnlinkedItems[]=
		{
			"V_TacVest_oli",
			"H_HelmetB_plain_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		weapons[]=
		{
			"OPTRE_m45",
			"Throw",
			"Put",
			"OPTRE_M6G_SF"
		};
		respawnWeapons[]=
		{
			"OPTRE_m45",
			"Throw",
			"Put",
			"OPTRE_M6G_SF"
		};
		magazines[]=
		{
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
		respawnMagazines[]=
		{
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_6Rnd_8Gauge_Pellets",
			"OPTRE_6Rnd_8Gauge_Slugs",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_green"
		};
	};
	class TripSeventh_OPFOR_Unarmed: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Unarmed";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
	};
	class TripSeventh_OPFOR_Officer: TripSeventh_OPFOR_Soldier_Base
	{
		dlc="OPTRE";
		scope=2;
		scopeCurator=2;
		displayName="Officer";
		uniformClass="OPTRE_Ins_ER_rolled_OD_blknred";
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_Cap_headphones",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		respawnlinkedItems[]=
		{
			"V_TacVest_oli",
			"H_Cap_headphones",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles",
			"OPTRE_Biofoam",
			"OPTRE_NVG"
		};
		weapons[]=
		{
			"OPTRE_M6G_SF",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_M6G_SF",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_orange",
			"OPTRE_M2_Smoke_green"
		};
		respawnMagazines[]=
		{
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_8Rnd_127x40_Mag_Tracer",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_orange",
			"OPTRE_M2_Smoke_green"
		};
		icon="iconManOfficer";
		identityTypes[]=
		{
			"LanguageENG_F",
			"LanguageENGB_F",
			"LanguageENGFRE_F",
			"LanguageGRE_F",
			"Kerry",
			"EPA_B_Northgate",
			"EPA_B_Hardy",
			"EPA_B_James",
			"EPA_B_McKay",
			"Head_Greek",
			"Head_African",
			"Head_Euro",
			"Head_Asian",
			"Head_NATO",
			"Head_Tanoan",
			"Head_Enoch",
			"Head_Russian",
			"G_INS_officer"
		};
	};
};

